### ISSUE TITLE
SKI10 Dataset Download

### ISSUE THREAD

**Issue by dntai** [gattia/ski10#1]
Nowadays, I am working in Bone Segmentation. Really, I want to download SKI10 Dataset for comparision my method. Would you like to share me the dataset?

**Comment by LeelaWo** [comment]
> Nowadays, I am working in Bone Segmentation. Really, I want to download SKI10 Dataset for comparision my method. Would you like to share me the dataset?

Hello, Did you get the dataset? Now I have download half of the dataset on Internate,  but miss the mask of the dataset. If you have any informations please let me know, Thanks!!

**Comment by CristinaMano** [comment]
Hi all,
Where could I get the SKI10 100 patients dataset ? I would appreciate if you could provide a link for this. Thanks a lot
